### PR TITLE
Fix maintainer name spelling

### PR DESCRIPTION
**Pull request by yalh76**

### CODE REVIEW

**Comment by yalh76** [comment]
@YunoHost-Apps/apps-group if someone can merge that tiny PR :) 

Thanks in advance

**Comment by tituspijean** [comment]
I am a bit weirded out by being corrected on how to spell my own username, but eh, I use both spellings.

**Comment by kay0u** [comment]
The goal of this PR, is more to fix   bug from our side:

https://dash.yunohost.org/app_maintainer_dash/tituspijean

(In the drop-down menu, we have two spellings for your username).

I'll try to find some time to fix this bug :-)

**Comment by tituspijean** [comment]
Ah! Indeed your motivation was not stated. Keep me updated regarding the bug on the dashboard, and choose whatever spelling is the most convenient to help you solve it. ;)

**Comment by kay0u** [comment]
In fact, there is a bug when the same person doesn't use exactly the same type across all his package like:

Kay0u / kay0u
Titus Pijean / tituspijean
...

**Pull request merged**
